language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dbarattini-pg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dbarattini-pg/docker-react yarn test